version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file:
      - backend/.env

  db:
    image: "postgres:alpine"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "edu_pulse"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      BACKEND_BASE_URL: "http://localhost:8080"
      NEXTAUTH_SECRET: "atr5-gt65-9jet"
      NEXTAUTH_URL: "http://localhost:3000/"
      NEXT_PUBLIC_BASE_URL: "http://localhost:3000"
      NODE_ENV: "development"
