version: '3'
services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file:
      - backend/.env
    networks:
      - edu-pulse-network

  db:
    container_name: db
    image: "postgres:alpine"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "edu_pulse"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - edu-pulse-network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
#      args:
#        BACKEND_BASE_URL: http://backend:8080
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      BACKEND_DOCKER_BASE_URL: "http://backend:8080"
      BACKEND_BASE_URL: "http://localhost:8080"
      NEXTAUTH_SECRET: "atr5-gt65-9jet"
      NEXTAUTH_URL: "http://localhost:3000/"
      NEXT_PUBLIC_BASE_URL: "http://localhost:3000"
      BASE_URL: "http://localhost:3000"
      NODE_ENV: "development"
    networks:
      - edu-pulse-network

networks:
  edu-pulse-network:
    driver: bridge

volumes:
  db-data: