version: '3'

services:
  api:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - my_network

  db:
    container_name: "db"
    image: "postgres:alpine"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "edu_pulse"
    networks:
      - my_network

networks:
  my_network:
    external: true
