apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 381492024252.dkr.ecr.us-east-1.amazonaws.com/edu-pulse-backend:latest
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@postgres-service:5432/edu_pulse"
          ports:
            - containerPort: 8080